### ISSUE TITLE
Tabs on tablets...

### ISSUE THREAD

**Issue by nishal** [ericalarcon/AndroidBasicFramework#3]
Not sure if this is a feature that wasn't intended.

Tabs on a tablet appear as small and centred unlike on phones where they fill up the width of the action bar when there are just a couple of tabs.

A possible quick fix in fragment_tabs for TabLayout:
```
app:tabMaxWidth="0dp"
app:tabGravity="fill"
```

Another possibility would be to add only `app:tabMaxWidth="0dp"` and leave the choice to control `tabGravity` in the extended class. That way classes that subclass can control the `tabGravity` giving more flexibility.

**Comment by ericalarcon** [comment]
I think this is the default bahaviour in tablets because if the app is in full screen the tabs would be giant. However, i think that in a master/detail layout it makes sense to fill up the full width of the master, so thanks for the fix. I will add it in the project as soon as i can.

**Comment by ericalarcon** [comment]
Issue solved.
